#!/bin/bash

#allows script to run as a crontab
# cp ./data/backup.sh /var/backups/mongo/backup.sh
# sudo chown root:toco /var/backups/mongo/backup.sh
# sudo chmod u+x /var/backups/mongo/backup.sh

#publish nodejs code
cd ../client
cp ../devops/test_client.env ./.env
npm install
npm run build

#build deno docker
cd ../server
cp ../devops/test_server.env ./.env

sudo docker stop stopserver
sudo docker build -t stopimage . --rm
sudo docker run -p 3000:3000 -t --rm --name stopserver -d -it stopimage

cd ..